global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "xelyra-backend"
    static_configs:
      - targets: ["host.docker.internal:3000"] # Use your backend port if not 3000
